"""add_column_price_from_items

Revision ID: 382c6df4a133
Revises: 669577174af0
Create Date: 2026-02-06 21:12:54.314960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382c6df4a133'
down_revision: Union[str, Sequence[str], None] = '669577174af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'price')
    # ### end Alembic commands ###
